name: GarryC
favicon: null
layout_spectrum: 0.31829913379624486
typography_spectrum: 0.9821787516120821
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.9057276125531644
  lightness: 0.2530298288911581
  saturation: 0.2505514733493328
  rhythmicContrast: 0.8293977361172438
purpose: []
